[package]
name = "L1"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
dashmap = "6.1.0"
flume = "0.11.0"
num = "0.4.3"
tokio = { version = "1.40.0", features = ["full", "sync"] }
tokio-util = "0.7.12"
