services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./persistant:/var/lib/postgresql/data
    ports:
      - "5432:5432"
